name: "x code review bot"
description: "Checks code review tasks on pull requests"
branding:
  color: blue
  icon: check-square
inputs:
  token:
    description: "GITHUB_TOKEN"
    default: ${{ github.token }}
    required: true
runs:
  using: "node16"
  main: "lib/index.js"
